export const OrganisingTeam = [
  {
    img: "/image/10.jpeg",
    role: "Chief Patron",
    name: "Hon'ble Dr.Ashok K.Chauhan",
    job: "Founder President",
    about: "Amity Education Group",
  },
  {
    img: "/image/16.jpeg",
    role: "Chief Patron",
    name: "Hon'ble Dr.Atul Chauhan",
    job: "Chancellor",
    about: "Amity Education Group",
  },
  {
    img: "/image/17.jpeg",
    role: "Mentor",
    name: "Mr. U Ramachandan",
    job: "Sr. Vice President",
    about: "Amity Education Group",
  },
  {
    img: "/image/13.jpeg",
    role: "Mentor",
    name: "Mr. Gaurav Gupta",
    job: "Vice President ",
    about: "Amity Education Group",
  },
  {
    img: "/image/14.jpeg",
    role: "Patron",
    name: "Dr. Vivekanand Pandey",
    job: "Pro Vice Chancellor",
    about: "Amity University Patna",
  },
  {
    img: "/image/15.jpeg",
    role: "Patron",
    name: "Mr. Siddharth Shankar",
    job: "Deputy Registrar",
    about: "Amity University Patna",
  },
  {
    img: "/image/12.jpeg",
    role: "Patron",
    name: "Dr. Sushil Kumar",
    job: "Dy. Controller of Exam",
    about: "Amity University Patna",
  },
  {
    img: "/image/2.jpeg",
    role: "Advisory Committe Member",
    name: "Dr. Shashi Bhushan",
    job: "Director, ASET",
    about: "Amity University Patna",
  },
  {
    img: "/image/1.jpeg",
    role: "Convenor",
    name: "Prof. Nikhil Sharma",
    job: "Program Leader (ASET)",
    about: "Amity University Patna",
  },
  {
    img: "/image/mam.jpg",
    role: "Convenor",
    name: "Dr. Shilpi Singh",
    job: "Asst. Professor (ASET)",
    about: "Amity University Patna",
  },
  {
    img: "/image/4.jpeg",
    role: "Co-Convenor",
    name: "Prof. Ravi Shekhar",
    job: "Asst. Professor (ASET)",
    about: "Amity University Patna",
  },
];

export const Developers = [
  {
    img: "/image/harsh.jpeg",
    role: "Developer",
    name: "Harsh Chauhan",
    about: "Amity University Patna",
  },
  {
    img: "/image/rimm.jpeg",
    role: "Developer",
    name: "Rimjhim Kumari",
    about: "Amity University Patna",
  },
  {
    img: "/image/gaurav.jpg",
    role: "Developer",
    name: "Gaurav Kumar Thakur",
    about: "Amity University Patna",
  },
  {
    img: "/image/an.jpeg",
    role: "Video Editor",
    name: "Anant kumar",
    about: "Amity University Patna",
  },
];

export const Members = [
  {
    img: "/image/11.jpeg",
    role: "Student Coordinator",
    name: "Nadra Hoda",
    about: "Amity University Patna",
  },
  {
    img: "/image/6.jpeg",
    role: "Student Coordinator",
    name: "Pranit Singh",
    about: "Amity University Patna",
  },
  {
    img: "/image/3.jpeg",
    role: "Student Coordinator",
    name: "Kumar Mohit",
    about: "Amity University Patna",
  },
  {
    img: "/image/9.jpeg",
    role: "Student Coordinator",
    name: "Shalini Verma",
    about: "Amity University Patna",
  },
  {
    img: "/image/nu.jpeg",
    role: "Organiser",
    name: "Nupur Raj",
    about: "Amity University Patna",
  },

  {
    img: "/image/Kan.jpeg",
    role: "Organiser",
    name: "Kanishka",
    about: "Amity University Patna",
  },
  {
    img: "/image/jj.png",
    role: "Organiser",
    name: "Jagriti Kumari",
    about: "Amity University Patna",
  },
  {
    img: "/image/aman.jpg",
    role: "Organiser",
    name: "Aman Singh",
    about: "Amity University Patna",
  },
  {
    img: "/image/Mohit.jpeg",
    role: "Organiser",
    name: "Mohit kumar",
    about: "Amity University Patna",
  },
  {
    img: "/image/Rahul.jpeg",
    role: "Organiser",
    name: "Rahul",
    about: "Amity University Patna",
  },
  {
    img: "/image/8.jpeg",
    role: "Organiser",
    name: "Ankur",
    about: "Amity University Patna",
  },
  {
    img: "/image/ss.jpg",
    role: "Organiser",
    name: "Shubham Kumar Jha",
    about: "Amity University Patna",
  },
  {
    img: "/image/p.jpeg",
    role: "Organiser",
    name: "Pragati bhardwaj",
    about: "Amity University Patna",
  },
  {
    img: "/image/r.jpeg",
    role: "Organiser",
    name: "Raushan",
    about: "Amity University Patna",
  },
  {
    img: "/image/s.jpeg",
    role: "Organiser",
    name: "Shubham Raj",
    about: "Amity University Patna",
  },
  {
    img: "/image/Seemi.jpeg",
    role: "Organiser",
    name: "Seemi",
    about: "Amity University Patna",
  },
  {
    img: "/image/samrat.jpeg",
    role: "Organiser",
    name: "Samrat",
    about: "Amity University Patna",
  },
  {
    img: "/image/pr.jpeg",
    role: "Organiser",
    name: "Priyanshu",
    about: "Amity University Patna",
  },
  {
    img: "/image/Adarsh.jpeg",
    role: "Organiser",
    name: "Adarsh Raj",
    about: "Amity University Patna",
  },
  {
    img: "/image/Manshi Rathour.jpeg",
    role: "Organiser",
    name: "Manshi Rathour",
    about: "Amity University Patna",
  },
  {
    img: "/image/Bajrang.jpeg",
    role: "Organiser",
    name: "Bajrang kumar",
    about: "Amity University Patna",
  },
  {
    img: "/image/Saumya Singh.jpeg",
    role: "Organiser",
    name: "Saumya singh",
    about: "Amity University Patna",
  },

  {
    img: "/image/abh.jpg",
    role: "Organiser",
    name: "Abhyudai Shrivastav",
    about: "Amity University Patna",
  },
];
